// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/resources-page/CardWall.tsx": () => import("../components/mockups/resources-page/CardWall.tsx"),
  "./components/mockups/resources-page/MagazineGrid.tsx": () => import("../components/mockups/resources-page/MagazineGrid.tsx"),
  "./components/mockups/resources-page/SidebarFilter.tsx": () => import("../components/mockups/resources-page/SidebarFilter.tsx")
};
